/*
 * Chuck SWAPI API
 *
 * .NET CORE C# Chuck SWAPI Project API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: don@obeyi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using chuckswapi.Attributes;

using Microsoft.AspNetCore.Authorization;
using chuckswapi.Models;

namespace chuckswapi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ChuckApiController : ControllerBase
    { 
        /// <summary>
        /// Returns a list of Joke categories
        /// </summary>
        /// <remarks>animal,career,celebrity,dev</remarks>
        /// <response code="0">successful operation</response>
        [HttpPost]
        [Route("/donPabloNow/donPabloNow/1.0.0/chuck/categories")]
        [ValidateModelState]
        [SwaggerOperation("ChuckCategories")]
        public virtual IActionResult ChuckCategories()
        { 
            //TODO: Uncomment the next line to return response 0 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(0);


            throw new NotImplementedException();
        }
    }
}
