/*
 * Chuck SWAPI API
 *
 * .NET CORE C# Chuck SWAPI Project API.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: don@obeyi.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using chuckswapi.Attributes;

using Microsoft.AspNetCore.Authorization;
using chuckswapi.Models;

namespace chuckswapi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SwapiApiController : ControllerBase
    { 
        /// <summary>
        /// Returns a list os Star Wars People
        /// </summary>
        /// <remarks>-[name:Luke Skywalker,...]-</remarks>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/donPabloNow/donPabloNow/1.0.0/swapi/people")]
        [ValidateModelState]
        [SwaggerOperation("SwapiPeople")]
        public virtual IActionResult SwapiPeople()
        { 
            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405);


            throw new NotImplementedException();
        }
    }
}
