#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/chuckswapi_api/ && \
    dotnet build src/chuckswapi_api/ && \
    echo "Now, run the following to start the project: dotnet run -p src/chuckswapi_api/chuckswapi_api.csproj --launch-profile web"
